### PR TITLE
Add support for commit date in the output

### LINKED ISSUE #16: Add the ability to include SHA date to the version
`ember-cli-app-version` has an [issue](https://github.com/EmberSherpa/ember-cli-app-version/issues/50) and a [PR](https://github.com/EmberSherpa/ember-cli-app-version/pull/51#pullrequestreview-66370957) to allow displaying SHA date in the version. 

The current PR spawns a system process with a `git` call. It would be better to have `git-repo-version` optionally include the date in the version. 

`git-repo-info` already provides [`authorDate`](https://github.com/rwjblue/git-repo-info#usage) we just need to include it.

Would you accept a PR with this functionality?

### PR DESCRIPTION
**Pull request by ondrejsevcik**
Fixes #16 

@cibernox  I moved second parameter (`root`) into the options object. It wasn't mentioned in the README so I thought it's undocumented feature thus it shouldn't be breaking change. Let me know what do you think about it. 

Thank you

### CODE REVIEW

**Comment by cibernox** [comment]
To be honest, I have no clue if anyone was/is using that. Would you mind making the function polymorphic?
If the second argument is an POJO, it can have `root` and `includeDate` keys. If the second argument is something other than a POJO, then it's the root. That way it would be 100% backwards compatible and still have a decent API.

**Comment by ondrejsevcik** [comment]
I can do that, but before I do so, I would like to know why do you want to keep this function backward compatible. Wouldn't it be much easier and cleaner to simply refactor it into the format 
```js
getVersion({
  shaLength: 10,
  includeDate: true,
  root: '/path'
});
```
? I think that upgrade path is very easy for existing users. I can also create CHANGELOG for that. 

What do you think?

**Comment by cibernox** [comment]
If we bump a number that also works form me

**Comment by ondrejsevcik** [comment]
Okay, it's accepting one option object 
```js
getVersion({
  shaLength: 8,
  includeDate: true,
  projectPath: '../tmp'
});
```
- version bumped
- README edited
- added tests

This PR should also solve #15 as it is possible to exclude sha in the output by setting shaLength to zero.

Let me know whether there is something else. Thank you

**Comment by cibernox** [comment]
It looks good. I'll release a new version now.

**Comment by cibernox** [comment]
Released a 1.0.0

**Comment by ondrejsevcik** [comment]
awesome 👍

**Pull request merged**
